const LANGUAGE_LEVELS={JA:['Foundation Japanese I','Foundation Japanese II','Foundation Japanese III','Intermediate Japanese','Pre-Advanced Japanese','Advanced Japanese'],EN:['Elementary English','Pre-Intermediate English','Intermediate English','Upper-Intermediate English','Advanced English 1','Advanced English 2']};
function basisLanguage(){return $('track').value==='E'?'EN':'JA';}
function studyLanguage(){return basisLanguage()==='EN'?'JA':'EN';}
function basisLabel(){return basisLanguage()==='EN'?'English Basis':'Japanese Basis';}
function updateLanguageLevelOptions(value=0){const lang=studyLanguage(),labels=LANGUAGE_LEVELS[lang],select=$('languageLevel'),keep=Number(value||0);select.innerHTML='<option value="0">이수 완료 없음</option>'+labels.map((label,i)=>`<option value="${i+1}">${esc(label)}</option>`).join('');select.value=String(Math.min(Math.max(keep,0),labels.length));$('languageLevelLabel').textContent=`${lang==='JA'?'Japanese':'English'} · 이수 완료 최고 레벨`;$('languageLevelHelp').textContent=(lang==='JA'?'English Basis: Japanese 단계 수업에서 선택한 완료 레벨 이하를 자동 제외합니다.':'Japanese Basis: English 단계 수업에서 선택한 완료 레벨 이하를 자동 제외합니다.'+($('track').value==='JAT'?' Advanced Track은 Standard 단계가 자동 제외됩니다.':''))+' 대학 승인·자동배정 예외는 아래 확정 수업에 Class code로 추가하면 유지됩니다.';}
function semesterUnavailableReason(section){const min=Number(section?.availableFromSemester||subjectOfSection(section)?.availableFromSemester||0);return min&&Number($('semesterLevel').value)<min?`${min} Semester부터 수강 가능`:'';}
function languageUnavailableReason(section){const subject=subjectOfSection(section),core=section?.languageCore||subject?.languageCore,rank=Number(section?.languageLevelRank||subject?.languageLevelRank||0),label=section?.languageLevelLabel||subject?.languageLevelLabel||section?.name||'언어 수업';if(!core||!rank)return'';const track=$('track').value;if(track==='E'&&core==='EN')return'English Basis · 단계형 English 수업 제외';if((track==='JST'||track==='JAT')&&core==='JA')return'Japanese Basis · 단계형 Japanese 수업 제외';let completed=Number($('languageLevel').value||0);if(track==='JAT'&&core==='EN')completed=Math.max(completed,4);const opposite=(track==='E'&&core==='JA')||((track==='JST'||track==='JAT')&&core==='EN');if(opposite&&completed&&rank<=completed)return`${label} · 이수 완료 레벨 이하`;return'';}
function eligibilitySummary(){const level=Number($('languageLevel').value||0),labels=LANGUAGE_LEVELS[studyLanguage()],levelText=level?` · ${labels[level-1]} 이하 제외`:'';return`${$('semesterLevel').value} Semester · ${basisLabel()}${levelText}`;}

eligible=function(section){return !semesterUnavailableReason(section)&&!languageUnavailableReason(section);};
unavailableReason=function(section){return semesterUnavailableReason(section)||languageUnavailableReason(section);};

save=function(){localStorage.setItem(prefsKey(),JSON.stringify({college:college(),semesterLevel:$('semesterLevel').value,track:$('track').value,languageLevel:$('languageLevel').value,accelerated:$('accelerated').checked,targetCredits:$('targetCredits').value,selectedCodes:state.selectedCodes,universityCodes:state.universityCodes,blockedSlots:[...state.blockedSlots],quarter:state.quarter}));};
loadPrefs=function(){try{const newer=JSON.parse(localStorage.getItem(prefsKey())||'null');const old=JSON.parse(localStorage.getItem('apu-schedule-prefs-v04')||'null');const p=newer||old||{};if(p.college)$('college').value=p.college;if(p.semesterLevel)$('semesterLevel').value=p.semesterLevel;if(p.track)$('track').value=p.track;updateLanguageLevelOptions(p.languageLevel||0);if(p.accelerated!==undefined)$('accelerated').checked=!!p.accelerated;if(p.targetCredits)$('targetCredits').value=p.targetCredits;state.selectedCodes=Array.isArray(p.selectedCodes)?p.selectedCodes.map(String):[];state.universityCodes=Array.isArray(p.universityCodes)?p.universityCodes.map(String):(Array.isArray(p.fixedCodes)?p.fixedCodes.map(String):[]);state.blockedSlots=new Set(Array.isArray(p.blockedSlots)?p.blockedSlots:[]);state.quarter=p.quarter||p.availabilityQuarter||'Q1'}catch{updateLanguageLevelOptions(0)}};

addUniversity=function(raw){const code=String(raw||'').trim();const section=sectionByCode(code);if(!section){toast(`Class code ${code}를 찾지 못했습니다.`,true);return}const semesterReason=semesterUnavailableReason(section);if(semesterReason){toast(semesterReason,true);return}const lockedConflict=universitySections().find(s=>s.classCode!==section.classCode&&(hasConflict(s,section)||s.subjectCode===section.subjectCode));if(lockedConflict){toast('다른 확정수업과 충돌합니다.',true);return}const collisions=selectedSections().filter(s=>hasConflict(s,section)||s.subjectCode===section.subjectCode);if(collisions.length&&!confirm(`확정수업과 겹치는 선택 수업 ${collisions.map(s=>s.name).join(', ')}을 제거할까요?`))return;for(const key of sectionSlots(section))state.blockedSlots.delete(key);const remove=new Set(collisions.map(s=>String(s.classCode)));state.selectedCodes=state.selectedCodes.filter(c=>!remove.has(c));if(!state.universityCodes.includes(code))state.universityCodes.push(code);save();$('universityCode').value='';renderAll();};
revalidateSemesterSelection=function(){if(!state.data)return;const invalid=selectedSections().filter(s=>!eligible(s));if(invalid.length){const bad=new Set(invalid.map(s=>String(s.classCode)));state.selectedCodes=state.selectedCodes.filter(c=>!bad.has(c));toast(`개인 수강 기준 변경으로 ${invalid.length}개 선택 수업을 제거했습니다.`,true)}const invalidLocked=universitySections().filter(s=>!!semesterUnavailableReason(s));if(invalidLocked.length)toast(`확정수업 ${invalidLocked.length}개가 현재 Semester 기준과 맞지 않습니다.`,true);};
buildAutofillConfig=function(){const fixed=[...new Set([...state.universityCodes,...state.selectedCodes])];return{college:college(),semesterLevel:Number($('semesterLevel').value),accelerated:$('accelerated').checked,track:$('track').value,languageLevel:Number($('languageLevel').value||0),targetCredits:Number($('targetCredits').value),maxCredits:maxCredits(),fixedClassCodes:fixed,blockedSlots:[...state.blockedSlots],autofill:true,maxCampusDays:5,maxGap:5,statuses:{}};};

const _afterDataProfile=afterData;
afterData=function(){_afterDataProfile();$('eligibilityText').textContent=eligibilitySummary();};
aplusLink=function(s,detail=false){const a=s?.aplusReview;if(!a)return'';const count=Number(a.reviewCount||0),rating=Number(a.rating),recommend=a.recommendPercent;const hasRating=count&&Number.isFinite(rating);const scoreText=hasRating?rating.toFixed(1):'N/A';const reviewText=count?`${count} review${count===1?'':'s'}`:'리뷰 없음';const recommendText=count&&recommend!==null&&recommend!==undefined?`추천 ${recommend}%`:'';const href=esc(a.sourceUrl||'https://apluscoursereview.com/');const meta=[`<span class="aplus-brand">A+</span>`,`<span>${reviewText}</span>`];if(recommendText)meta.push(`<span>${recommendText}</span>`);meta.push('<span class="aplus-arrow">↗</span>');const link=`<a class="aplus-badge${detail?' detail':''}" href="${href}" target="_blank" rel="noopener noreferrer" onclick="event.stopPropagation()" title="A+ Course Review 열기"><span class="aplus-main"><span class="aplus-star">★</span><span class="aplus-score">${scoreText}</span></span><span class="aplus-meta">${meta.join('<span class="aplus-dot">·</span>')}</span></a>`;return detail?`<div class="aplus-row detail">${link}</div>`:`<div class="aplus-row">${link}</div>`;};

$('track').addEventListener('change',()=>updateLanguageLevelOptions(0));
$('languageLevel').addEventListener('change',()=>{state.previewCodes=[];revalidateSemesterSelection();save();$('eligibilityText').textContent=eligibilitySummary();renderAll();});
