function setDataStatus(text,ok=false){$('dataBadge').textContent=text;$('dataBadge').className=`top-chip${ok?' good':''}`;$('loadStatus').textContent=text;$('loadStatus').className=`status-box${ok?' ok':''}`;}

function totalCredits(sections){const seen=new Set();let total=0;for(const s of sections){if(seen.has(s.subjectCode))continue;seen.add(s.subjectCode);total+=credits(s)}return total;}
function renderTop(){clampTarget();$('profileButton').textContent=`${college()} · ${$('semesterLevel').value} Semester`;const view=allDisplayedSections(),preview=state.previewCodes.length>0;$('planHeading').textContent=preview?'내 시간표 · 대안 미리보기':'내 시간표';$('creditMetric').textContent=`${fmtCredits(preview?totalCredits(view):currentCredits())} / ${maxCredits()}`;$('classMetric').textContent=String(view.length);$('myCount').textContent=String(baseSections().length);const metrics=calendarMetrics(view);$('daysMetric').textContent=`${metrics.days}일`;$('gapMetric').textContent=String(metrics.gaps);document.querySelectorAll('[data-quarter]').forEach(b=>b.classList.toggle('active',b.dataset.quarter===state.quarter));$('quarterHelp').textContent=`${state.quarter==='Q1'?'1Q':'2Q'} 시간표${preview?' · 미리보기':''}`;}
function calendarMetrics(sections){const byDay=new Map();for(const s of sections){if(!(s.term==='SEMESTER'||s.term===state.quarter))continue;for(const m of s.meetings||[]){if(!byDay.has(m.day))byDay.set(m.day,new Set());byDay.get(m.day).add(Number(m.period));}}let gaps=0;for(const ps of byDay.values()){const a=[...ps].sort((x,y)=>x-y);for(let i=1;i<a.length;i++)gaps+=Math.max(0,a[i]-a[i-1]-1)}return{days:byDay.size,gaps};}
function aplusLink(s,detail=false){const a=s?.aplusReview;if(!a)return'';const count=Number(a.reviewCount||0),rating=Number(a.rating),recommend=a.recommendPercent;const ratingText=count&&Number.isFinite(rating)?`★ ${rating.toFixed(1)}`:'리뷰 없음';const reviewText=count?` · ${count} review${count===1?'':'s'}`:'';const recommendText=count&&recommend!==null&&recommend!==undefined?` · 추천 ${recommend}%`:'';const link=`<a class="tag lang" href="${esc(a.sourceUrl||'https://apluscoursereview.com/')}" target="_blank" rel="noopener noreferrer" onclick="event.stopPropagation()" style="text-decoration:none">A+ · ${ratingText}${reviewText}${recommendText} ↗</a>`;return detail?`<div class="class-tags" style="margin-top:12px">${link}</div>`:`<div class="class-tags">${link}</div>`;}

function classAvailability(section){if(!eligible(section))return{ok:false,reason:unavailableReason(section)};if(blockedConflict(section))return{ok:false,reason:'비워둔 시간과 겹침'};const same=baseSections().find(s=>s.subjectCode===section.subjectCode&&s.classCode!==section.classCode);if(same)return{ok:false,reason:`같은 과목의 Class ${same.classCode} 선택됨`,replace:same};const conflict=baseSections().find(s=>s.classCode!==section.classCode&&hasConflict(s,section));if(conflict)return{ok:false,reason:`${conflict.name}과 시간 겹침`,conflict};const already=baseSections().some(s=>s.classCode===section.classCode);if(!already&&currentCredits()+credits(section)>maxCredits())return{ok:false,reason:`학점 상한 ${maxCredits()} 초과`};return{ok:true};}
function addClass(code){const section=sectionByCode(code);if(!section)return;if(!eligible(section)){toast(unavailableReason(section),true);return}if(blockedConflict(section)){toast('비워둔 시간과 겹칩니다.',true);return}const existing=baseSections().find(s=>s.subjectCode===section.subjectCode&&s.classCode!==section.classCode);if(existing&&state.universityCodes.includes(String(existing.classCode))){toast('같은 과목의 확정 수업이 이미 있습니다.',true);return}const others=baseSections().filter(s=>!existing||s.classCode!==existing.classCode);const conflict=others.find(s=>s.classCode!==section.classCode&&hasConflict(s,section));if(conflict){toast(`${conflict.name}과 시간이 겹칩니다.`,true);return}const nextCredits=currentCredits()-(existing?credits(existing):0)+credits(section);if(!baseSections().some(s=>s.classCode===section.classCode)&&nextCredits>maxCredits()){toast(`학점 상한 ${maxCredits()}을 넘습니다.`,true);return}if(existing&&!confirm(`${existing.name}의 Class ${existing.classCode} 대신 Class ${section.classCode}로 바꿀까요?`))return;if(existing)state.selectedCodes=state.selectedCodes.filter(c=>c!==String(existing.classCode));if(!state.selectedCodes.includes(String(code))&&!state.universityCodes.includes(String(code)))state.selectedCodes.push(String(code));state.previewCodes=[];save();renderAll();toast(`${section.name} · Class ${section.classCode} 추가`);}
function removeClass(code){state.selectedCodes=state.selectedCodes.filter(c=>c!==String(code));state.previewCodes=[];save();renderAll();}
function addUniversity(raw){const code=String(raw||'').trim();const section=sectionByCode(code);if(!section){toast(`Class code ${code}를 찾지 못했습니다.`,true);return}if(!eligible(section)){toast(unavailableReason(section),true);return}const lockedConflict=universitySections().find(s=>s.classCode!==section.classCode&&(hasConflict(s,section)||s.subjectCode===section.subjectCode));if(lockedConflict){toast('다른 확정수업과 충돌합니다.',true);return}const collisions=selectedSections().filter(s=>hasConflict(s,section)||s.subjectCode===section.subjectCode);if(collisions.length&&!confirm(`확정수업과 겹치는 선택 수업 ${collisions.map(s=>s.name).join(', ')}을 제거할까요?`))return;for(const key of sectionSlots(section))state.blockedSlots.delete(key);const remove=new Set(collisions.map(s=>String(s.classCode)));state.selectedCodes=state.selectedCodes.filter(c=>!remove.has(c));if(!state.universityCodes.includes(code))state.universityCodes.push(code);save();$('universityCode').value='';renderAll();}
function removeUniversity(code){state.universityCodes=state.universityCodes.filter(c=>c!==String(code));save();renderAll();}

function filteredSubjectGroups(){if(!state.data)return[];const q=$('search').value.trim().toLowerCase(),term=$('termFilter').value,lang=$('languageFilter').value,show=$('showUnavailable').checked;const groups=[];for(const subject of state.data.subjects){const sections=subject.sections.filter(s=>{const searchable=`${subject.name} ${s.name} ${s.instructor||''} ${s.classCode} ${s.subjectCd||''}`.toLowerCase();if(q&&!searchable.includes(q))return false;if(term&&s.term!==term)return false;if(lang&&s.language!==lang)return false;if(!show&&!eligible(s))return false;if(state.slotFilter){const sf=state.slotFilter;if(!(s.term==='SEMESTER'||s.term===sf.quarter))return false;if(!(s.meetings||[]).some(m=>m.day===sf.day&&Number(m.period)===sf.period))return false}return true});if(sections.length)groups.push({subject,sections})}return groups;}
function renderCourseList(){if(!state.data){$('courseList').innerHTML='<div class="empty">APU 데이터를 불러오세요.</div>';return}const groups=filteredSubjectGroups();const sectionCount=groups.reduce((n,g)=>n+g.sections.length,0);$('listSummary').textContent=`${groups.length}과목 · ${sectionCount}개 Class`;const html=groups.map(({subject,sections})=>`<section class="subject-group"><div class="subject-head"><div class="subject-title-row"><div><div class="subject-title">${esc(subject.name)}</div><div class="subject-meta"><span class="class-count">${sections.length}개 Class</span>${subject.field?`<span>· ${esc(subject.field)}</span>`:''}${subject.area?`<span>· ${esc(subject.area)}</span>`:''}${subject.availableFromSemester?`<span>· ${subject.availableFromSemester} Semester+</span>`:''}</div></div><span class="subject-credits">${fmtCredits(subject.credits)} cr</span></div></div><div class="class-list">${sections.map(renderClassCard).join('')}</div></section>`).join('');$('courseList').innerHTML=html||'<div class="empty">조건에 맞는 수업이 없습니다.</div>';}
function renderClassCard(s){const selected=state.selectedCodes.includes(String(s.classCode)),locked=state.universityCodes.includes(String(s.classCode)),issue=classAvailability(s),isUnavailable=!eligible(s),subject=subjectOfSection(s),prereq=subject?.prerequisites?.[$('track').value];const disabled=!selected&&!locked&&!issue.ok&&!issue.replace;return `<article class="class-card ${selected?'selected':''} ${locked?'locked':''} ${isUnavailable?'disabled':''}" data-open-class="${esc(s.classCode)}"><div><div class="class-card-head"><span class="class-code">Class ${esc(s.classCode)}</span>${locked?'<span class="class-lock">● 확정</span>':''}${selected&&!locked?'<span class="class-lock" style="color:var(--blue-strong)">● 선택됨</span>':''}</div><div class="class-teacher">${esc(s.instructor||'담당교수 미정')}</div>${aplusLink(s)}<div class="class-meetings"><span class="meeting-label">시간</span>${esc(meetingText(s))}</div><div class="class-tags"><span class="tag q">${esc(s.term)}</span>${s.language?`<span class="tag lang">${esc(s.language)}</span>`:''}${s.mode&&s.mode!=='UNKNOWN'?`<span class="tag">${esc(s.mode)}</span>`:''}${prereq?'<span class="tag warn">선수조건 확인</span>':''}</div>${disabled?`<div class="reason">${esc(issue.reason)}</div>`:''}</div><div class="class-actions"><button class="syllabus-action" data-syllabus="${esc(s.classCode)}" title="${s.syllabusUrl?'이 Class의 실라버스 상세 페이지 바로 열기':'APU 실라버스 검색 열기'}">${s.syllabusUrl?'실라버스 바로가기 ↗':'실라버스 검색 ↗'}</button><button class="class-action ${selected?'remove':''}" data-class-action="${esc(s.classCode)}" ${locked||disabled?'disabled':''}>${locked?'확정':selected?'제거':issue.replace?'교체':'추가'}</button></div></article>`;}
function renderMyList(){if(!state.data)return;const locked=universitySections(),chosen=selectedSections();let html='';if(locked.length){html+='<div class="my-section-title">확정 수업</div>'+locked.map(s=>`<div class="my-card locked" data-open-class="${esc(s.classCode)}"><div><strong>${esc(s.name)}</strong><span>Class ${esc(s.classCode)} · ${esc(meetingText(s))}</span></div></div>`).join('')}if(chosen.length){html+='<div class="my-section-title">내가 고른 수업</div>'+chosen.map(s=>`<div class="my-card" data-open-class="${esc(s.classCode)}"><div><strong>${esc(s.name)}</strong><span>Class ${esc(s.classCode)} · ${esc(meetingText(s))}</span></div><button data-remove-class="${esc(s.classCode)}">제거</button></div>`).join('')}if(!locked.length&&!chosen.length)html='<div class="empty">아직 선택한 수업이 없습니다.<br>수업 찾기에서 실제 Class를 추가하세요.</div>';$('myList').innerHTML=html;}

function renderCalendar(){const q=state.quarter,sections=allDisplayedSections();const cellMap={};for(const d of DAYS)for(let p=1;p<=6;p++)cellMap[`${d}:${p}`]=[];for(const s of sections){if(!(s.term==='SEMESTER'||s.term===q))continue;for(const m of s.meetings||[])if(cellMap[`${m.day}:${m.period}`])cellMap[`${m.day}:${m.period}`].push(s)}let html='<table class="calendar"><thead><tr><th></th>'+DAYS.map(d=>`<th>${DAY_KO[d]}요일</th>`).join('')+'</tr></thead><tbody>';for(let p=1;p<=6;p++){html+=`<tr><td class="period">${p}교시</td>`;for(const d of DAYS){const key=slotKey(q,d,p),arr=cellMap[`${d}:${p}`],blocked=state.blockedSlots.has(key),active=state.slotFilter?.quarter===q&&state.slotFilter?.day===d&&state.slotFilter?.period===p;html+=`<td class="slot ${blocked?'blocked':arr.length?'':'empty-slot'} ${active?'slot-active':''}" data-slot="${key}">`;if(arr.length)html+=arr.map(s=>`<div class="meeting-card ${state.universityCodes.includes(String(s.classCode))?'locked':''} ${state.previewCodes.length&&!state.selectedCodes.includes(String(s.classCode))&&!state.universityCodes.includes(String(s.classCode))?'preview':''} ${state.detailCode===String(s.classCode)?'active':''}" data-open-class="${esc(s.classCode)}"><strong>${esc(s.name)}</strong><span>Class ${esc(s.classCode)}</span></div>`).join('');else if(!blocked){if(state.activeSlot===key)html+=`<div class="slot-popover"><strong>${DAY_KO[d]}요일 ${p}교시</strong><button data-find-slot="${key}">이 시간에 열리는 수업 찾기</button><button data-block-slot="${key}">이 시간 비우기</button></div>`;else html+=`<button class="slot-hint" data-open-slot="${key}">클릭</button>`}html+='</td>'}html+='</tr>'}html+='</tbody></table>';$('calendar').innerHTML=html;renderTop();}
function setSlotFilter(key){if(!key){state.slotFilter=null}else{const [quarter,day,p]=key.split(':');state.slotFilter={quarter,day,period:Number(p)};state.quarter=quarter;state.tab='FIND';$('search').value=''}state.activeSlot=null;renderTabs();renderSlotFilter();renderCourseList();renderCalendar();}
function blockSlot(key){if(fixedOccupies(key)){toast('확정수업이 있는 시간은 비울 수 없습니다.',true);return}if(selectedOccupies(key)){toast('먼저 이 시간의 선택 수업을 제거하세요.',true);return}state.blockedSlots.add(key);state.activeSlot=null;save();renderAll();}
function unblockSlot(key){state.blockedSlots.delete(key);save();renderAll();}
function renderSlotFilter(){if(!state.slotFilter){$('slotFilter').classList.add('hidden');return}const sf=state.slotFilter;$('slotFilterText').textContent=`${sf.quarter} ${DAY_KO[sf.day]}요일 ${sf.period}교시 수업`;$('slotFilter').classList.remove('hidden');}

function renderTabs(){document.querySelectorAll('.sidebar-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));$('findPane').classList.toggle('hidden',state.tab!=='FIND');$('myPane').classList.toggle('hidden',state.tab!=='MY');}
function openDrawer(id){document.querySelectorAll('.drawer').forEach(d=>d.classList.remove('open'));$(id).classList.add('open');}
function closeDrawers(){document.querySelectorAll('.drawer').forEach(d=>d.classList.remove('open'));}
function openDetail(code){const s=sectionByCode(code);if(!s)return;state.detailCode=String(code);const subject=subjectOfSection(s),selected=state.selectedCodes.includes(String(code)),locked=state.universityCodes.includes(String(code)),issue=classAvailability(s);$('detailBody').innerHTML=`<div class="detail-title">${esc(s.name)}</div><div class="detail-sub">Class ${esc(s.classCode)} · ${esc(s.instructor||'담당교수 미정')}</div><div class="detail-grid"><div class="detail-item"><span>학점</span><strong>${fmtCredits(credits(s))}</strong></div><div class="detail-item"><span>기간</span><strong>${esc(s.term)}</strong></div><div class="detail-item"><span>언어</span><strong>${esc(s.language||'-')}</strong></div><div class="detail-item"><span>수업 형태</span><strong>${esc(s.mode||'-')}</strong></div></div>${aplusLink(s,true)}<div class="detail-meetings"><strong style="font-size:11px">이 Class의 전체 수업시간</strong>${(s.meetings||[]).map(m=>`<div class="detail-meeting">${DAY_KO[m.day]}요일 ${m.period}교시${m.classroom?` · ${esc(m.classroom)}`:''}</div>`).join('')||'<div class="detail-meeting">고정 시간 없음</div>'}</div>${subject?.prerequisites?.[$('track').value]?`<div class="danger-note" style="margin-top:14px">선수조건: ${esc(subject.prerequisites[$('track').value])}</div>`:''}<div class="drawer-actions"><button data-detail-syllabus="${esc(s.classCode)}">${s.syllabusUrl?'실라버스 바로가기 ↗':'실라버스 검색 ↗'}</button>${locked?'<button disabled>🔒 확정 수업</button>':selected?`<button class="remove" data-detail-remove="${esc(s.classCode)}">시간표에서 제거</button>`:`<button class="add" data-detail-add="${esc(s.classCode)}" ${!issue.ok&&!issue.replace?'disabled':''}>${issue.replace?'현재 Class 교체':'시간표에 추가'}</button>`}</div>${!locked&&!selected&&!issue.ok&&!issue.replace?`<div class="status-box err" style="margin-top:9px">${esc(issue.reason)}</div>`:''}`;openDrawer('detailDrawer');renderCalendar();}
function renderUniversity(){if(!state.data){$('universityList').innerHTML='';return}$('universityList').innerHTML=universitySections().map(s=>`<div class="fixed-chip"><span>${esc(s.name)} · ${esc(s.classCode)} · ${esc(meetingText(s))}</span><button data-remove-university="${esc(s.classCode)}">×</button></div>`).join('')||'<div class="empty-inline">등록된 확정 수업 없음</div>';}
function renderLanguages(){if(!state.data)return;const current=$('languageFilter').value;const values=[...new Set(state.data.sections.map(s=>s.language).filter(Boolean))].sort();$('languageFilter').innerHTML='<option value="">모든 언어</option>'+values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if(values.includes(current))$('languageFilter').value=current;}
function renderAll(){state.selectedCodes=state.selectedCodes.filter(c=>sectionByCode(c));state.universityCodes=state.universityCodes.filter(c=>sectionByCode(c));renderTop();renderTabs();renderSlotFilter();renderCourseList();renderMyList();renderCalendar();renderUniversity();}
function revalidateSemesterSelection(){if(!state.data)return;const invalid=selectedSections().filter(s=>!eligible(s));if(invalid.length){const bad=new Set(invalid.map(s=>String(s.classCode)));state.selectedCodes=state.selectedCodes.filter(c=>!bad.has(c));toast(`Semester 변경으로 ${invalid.length}개 선택 수업을 제거했습니다.`,true)}const invalidLocked=universitySections().filter(s=>!eligible(s));if(invalidLocked.length)toast(`확정수업 ${invalidLocked.length}개가 현재 Semester 기준과 맞지 않습니다.`,true);}

async function tryCached(){try{const r=await fetch(`/api/courses?college=${encodeURIComponent(college())}`);if(!r.ok)return false;state.data=await r.json();afterData();return true}catch{return false}}
async function loadOfficial(refresh=false){setDataStatus(refresh?'공식 데이터를 새로 받는 중...':'공식 데이터를 불러오는 중...');try{const r=await fetch('/api/load',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({college:college(),refresh})});const body=await r.json();if(!r.ok)throw new Error(body.error||'데이터 로드 실패');state.data=body;afterData();toast('APU 공식 데이터 로드 완료')}catch(e){setDataStatus(e.message,false);$('loadStatus').className='status-box err'}}
function updateSyllabusCoverage(){if(!state.data){$('syllabusSyncStatus').textContent='실라버스 링크: 데이터 로드 후 확인';return}const total=state.data.sections.length,direct=state.data.sections.filter(s=>s.syllabusUrl).length;$('syllabusSyncStatus').textContent=`실라버스 direct link · ${direct} / ${total}`;$('syllabusSyncStatus').className=`status-box${direct===total&&total?' ok':''}`;}
function afterData(){renderLanguages();const st=state.data.stats,term=state.data.term||'Academic term unknown',detected=state.data.academicTermDetected!==false;$('datasetTerm').textContent=detected?term:'학기 판별 필요';document.title=`APU Schedule Builder · ${detected?term:'Term unknown'}`;setDataStatus(detected?`${term} · ${st.subjects}과목 / ${st.sections}개 Class`:`학기 판별 실패 · ${st.subjects}과목 / ${st.sections}개 Class`,detected);if(!detected)toast('불러온 timetable에서 Spring/Fall을 확인하지 못했습니다. 파일 제목을 확인하세요.',true);$('eligibilityText').textContent=`${$('semesterLevel').value} Semester 기준 수업만 표시`;updateSyllabusCoverage();renderAll();save();}
async function syncSyllabi(){if(!state.data){toast('먼저 APU 공식 데이터를 불러오세요.',true);return}const b=$('syncSyllabusButton');b.disabled=true;b.textContent='동기화 중…';$('syllabusSyncStatus').textContent='Chrome/Edge에서 APU 실라버스 검색 중… 브라우저 창을 닫지 마세요.';try{const r=await fetch('/api/syllabus-sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({college:college(),headless:false})});const body=await r.json();if(!r.ok)throw new Error(body.error||'실라버스 동기화 실패');await tryCached();if(body.complete)toast(`실라버스 direct link ${body.found}/${body.total} 확보 완료`);else toast(`실라버스 ${body.found}/${body.total} 확보 · ${body.missing.length}개 미확보`,true)}catch(e){toast(e.message,true);updateSyllabusCoverage()}finally{b.disabled=false;b.textContent='실라버스 링크 전체 동기화'}}

function buildAutofillConfig(){const fixed=[...new Set([...state.universityCodes,...state.selectedCodes])];return{college:college(),semesterLevel:Number($('semesterLevel').value),accelerated:$('accelerated').checked,track:$('track').value,targetCredits:Number($('targetCredits').value),maxCredits:maxCredits(),fixedClassCodes:fixed,blockedSlots:[...state.blockedSlots],autofill:true,maxCampusDays:5,maxGap:5,statuses:{}};}
async function autofill(){if(!state.data)return;if(currentCredits()>=Number($('targetCredits').value)){toast('이미 목표 학점에 도달했습니다.');return}$('fillButton').disabled=true;$('fillButton').textContent='계산 중...';try{const r=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(buildAutofillConfig())});const body=await r.json();if(!r.ok)throw new Error(body.error||'계산 실패');if(!body.results?.length){toast(body.errors?.[0]||'가능한 조합이 없습니다.',true);return}renderSuggestions(body.results)}catch(e){toast(e.message,true)}finally{$('fillButton').disabled=false;$('fillButton').textContent='빈 학점 자동 채우기'}}
