function renderSuggestions(results){
  $('suggestList').innerHTML=results.map((r,i)=>{const newCount=r.courses.filter(c=>!state.universityCodes.includes(String(c.classCode))&&!state.selectedCodes.includes(String(c.classCode))).length;return `<div class="suggestion"><div><strong>${esc(tr('autofill.option',{number:i+1,credits:fmtCredits(r.credits)}))}</strong><span>${esc(tr('autofill.optionMeta',{days:r.metrics.campusDays,count:newCount}))}</span></div><button data-apply-suggestion="${i}">${esc(tr('autofill.preview'))}</button></div>`}).join('');
  $('suggestText').textContent=tr('autofill.goal',{credits:$('targetCredits').value});$('suggestions').classList.remove('hidden');$('suggestions')._results=results;
}
function previewSuggestion(i){const r=$('suggestions')._results?.[i];if(!r)return;state.previewCodes=r.courses.map(c=>String(c.classCode));renderCalendar();$('suggestions').querySelectorAll('[data-apply-suggestion]').forEach((b,j)=>{b.textContent=j===i?tr('autofill.apply'):tr('autofill.preview');b.dataset.previewed=j===i?'1':'0'});}
function applySuggestion(i){const r=$('suggestions')._results?.[i];if(!r)return;const fixed=new Set(state.universityCodes);state.selectedCodes=r.courses.map(c=>String(c.classCode)).filter(c=>!fixed.has(c));state.previewCodes=[];$('suggestions').classList.add('hidden');save();renderAll();toast(tr('autofill.applied'));}

function linkClassHover(code,on){document.querySelectorAll('[data-open-class]').forEach(el=>{if(String(el.dataset.openClass)===String(code))el.classList.toggle('is-linked',on)});}
function bindLinkedHover(container){container.addEventListener('mouseover',e=>{const el=e.target.closest('[data-open-class]');if(el)linkClassHover(el.dataset.openClass,true)});container.addEventListener('mouseout',e=>{const el=e.target.closest('[data-open-class]');if(!el)return;const next=e.relatedTarget?.closest?.('[data-open-class]');if(next&&next.dataset.openClass===el.dataset.openClass)return;linkClassHover(el.dataset.openClass,false)});}
$('themeButton').addEventListener('click',toggleTheme);
bindLinkedHover($('courseList'));bindLinkedHover($('myList'));bindLinkedHover($('calendar'));
document.querySelectorAll('.sidebar-tab').forEach(b=>b.addEventListener('click',()=>{state.tab=b.dataset.tab;renderTabs()}));
document.querySelectorAll('[data-quarter]').forEach(b=>b.addEventListener('click',()=>{state.quarter=b.dataset.quarter;state.activeSlot=null;save();renderCalendar()}));
$('presetSwitch').addEventListener('click',e=>{const b=e.target.closest('[data-preset]');if(b)activatePreset(b.dataset.preset)});
['search','termFilter','languageFilter','showUnavailable'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',renderCourseList));
$('clearSlotFilter').addEventListener('click',()=>setSlotFilter(null));
$('courseList').addEventListener('click',e=>{const syllabus=e.target.closest('[data-syllabus]');if(syllabus){e.stopPropagation();openSyllabus(syllabus.dataset.syllabus);return}const action=e.target.closest('[data-class-action]');if(action){e.stopPropagation();const code=action.dataset.classAction;if(state.selectedCodes.includes(code))removeClass(code);else addClass(code);return}const card=e.target.closest('[data-open-class]');if(card)openDetail(card.dataset.openClass)});
$('myList').addEventListener('click',e=>{const remove=e.target.closest('[data-remove-class]');if(remove){removeClass(remove.dataset.removeClass);return}const card=e.target.closest('[data-open-class]');if(card)openDetail(card.dataset.openClass)});
$('calendar').addEventListener('click',e=>{const cls=e.target.closest('[data-open-class]');if(cls){e.stopPropagation();openDetail(cls.dataset.openClass);return}const find=e.target.closest('[data-find-slot]');if(find){e.stopPropagation();setSlotFilter(find.dataset.findSlot);return}const block=e.target.closest('[data-block-slot]');if(block){e.stopPropagation();blockSlot(block.dataset.blockSlot);return}const cell=e.target.closest('[data-slot]');if(!cell)return;const key=cell.dataset.slot;if(state.blockedSlots.has(key)){unblockSlot(key);return}if(cell.querySelector('.meeting-card'))return;state.activeSlot=state.activeSlot===key?null:key;renderCalendar()});
$('settingsButton').addEventListener('click',()=>openDrawer('settingsDrawer'));$('profileButton').addEventListener('click',()=>openDrawer('settingsDrawer'));document.querySelectorAll('[data-close-drawer]').forEach(b=>b.addEventListener('click',closeDrawers));
$('detailBody').addEventListener('click',e=>{const syllabus=e.target.closest('[data-detail-syllabus]');if(syllabus){openSyllabus(syllabus.dataset.detailSyllabus);return}const add=e.target.closest('[data-detail-add]');if(add){addClass(add.dataset.detailAdd);closeDrawers()}const rem=e.target.closest('[data-detail-remove]');if(rem){removeClass(rem.dataset.detailRemove);closeDrawers()}});
$('addUniversityButton').addEventListener('click',()=>addUniversity($('universityCode').value));$('universityCode').addEventListener('keydown',e=>{if(e.key==='Enter')addUniversity(e.target.value)});$('universityList').addEventListener('click',e=>{const b=e.target.closest('[data-remove-university]');if(b)removeUniversity(b.dataset.removeUniversity)});
$('loadButton').addEventListener('click',()=>loadOfficial(false));$('refreshButton').addEventListener('click',()=>loadOfficial(true));
$('fillButton').addEventListener('click',autofill);
$('clearPlanButton').addEventListener('click',()=>{if(state.selectedCodes.length&&!confirm(tr('preset.clearConfirm',{preset:state.activePreset})))return;state.selectedCodes=[];state.previewCodes=[];save();renderAll();toast(tr('preset.cleared',{preset:state.activePreset}));});
$('closeSuggestions').addEventListener('click',()=>{state.previewCodes=[];$('suggestions').classList.add('hidden');renderCalendar()});$('suggestList').addEventListener('click',e=>{const b=e.target.closest('[data-apply-suggestion]');if(!b)return;const i=Number(b.dataset.applySuggestion);if(b.dataset.previewed==='1')applySuggestion(i);else previewSuggestion(i)});
['semesterLevel','track','accelerated','targetCredits'].forEach(id=>$(id).addEventListener('change',()=>{clampTarget();state.previewCodes=[];if(id==='semesterLevel'||id==='track')revalidateSemesterSelection();save();$('eligibilityText').textContent=eligibilitySummary();renderAll()}));
$('uiLanguage').addEventListener('change',()=>{const level=$('languageLevel').value;setLocale($('uiLanguage').value);applyTheme(document.documentElement.dataset.theme||'dark');updateLanguageLevelOptions(level);if(state.data)afterData();else{setDataStatus(tr('app.dataChecking'));$('eligibilityText').textContent=eligibilitySummary();renderAll();save();}});
$('college').addEventListener('change',async()=>{state.data=null;resetAllPresets();state.universityCodes=[];state.blockedSlots.clear();state.slotFilter=null;setDataStatus(tr('app.dataChecking'));save();renderAll();if(!await tryCached()){setDataStatus(tr('data.needLoad'));openDrawer('settingsDrawer')}});

document.addEventListener('keydown',e=>{if(e.key==='Escape'){state.activeSlot=null;closeDrawers();renderCalendar()}});
loadTheme();loadPrefs();applyStaticTranslations();clampTarget();renderTop();renderTabs();renderCalendar();tryCached().then(ok=>{if(!ok){setDataStatus(tr('data.needLoad'));openDrawer('settingsDrawer')}});
