const $=id=>document.getElementById(id);
const state={status:null,accepted:{}};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function now(){return new Date().toLocaleTimeString('ko-KR',{hour12:false});}
function log(level,message){const row=document.createElement('div');row.className=`log-line ${level||'info'}`;row.innerHTML=`<span class="time">${now()}</span>${esc(message)}`;$('log').appendChild(row);$('log').scrollTop=$('log').scrollHeight;}
function events(items){for(const item of items||[])log(item.level,item.message);}
async function api(path,options={}){const res=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const data=await res.json();if(!res.ok&&!data.error)data.error=`HTTP ${res.status}`;return data;}
function renderStatus(data){state.status=data;if(!data.ok){$('readerState').className='reader error';$('readerState').textContent=`Dataset 오류: ${data.error}`;events(data.events);return}$('datasetLabel').textContent=`${data.college} · ${data.term}`;$('classCount').textContent=data.stats.classes;$('mappedCount').textContent=data.stats.mapped;$('unmappedCount').textContent=data.stats.unmapped;$('problemCount').textContent=data.stats.invalid+data.stats.conflicts;$('batchTarget').textContent=`GitHub target: data/syllabus-links/${data.termSlug}/batch-XXX.json`;const reader=$('readerState');if(data.readerExpected===0){reader.className='reader warn';reader.textContent='아직 repository mapping이 없어 실제 연결 검증 대상이 없습니다.'}else if(data.readerVerified){reader.className='reader ok';reader.textContent=`앱 판독 확인됨 · repository mapping ${data.readerAttached}/${data.readerExpected} Class에 정확히 연결됨`}else{reader.className='reader error';reader.textContent=`앱 판독 불일치 · ${data.readerAttached}/${data.readerExpected} 연결 (${data.mismatches.length} mismatch)`}events(data.events);renderClasses();}
function renderClasses(){if(!state.status?.ok)return;const q=$('classSearch').value.trim().toLowerCase(),filter=$('statusFilter').value;const rows=state.status.classes.filter(row=>{if(filter==='mapped'&&!row.mapped)return false;if(filter==='unmapped'&&row.mapped)return false;if(q&&!`${row.classCode} ${row.name} ${row.instructor}`.toLowerCase().includes(q))return false;return true});$('classRows').innerHTML=rows.map(row=>`<tr><td><span class="pill ${row.mapped?'ok':'missing'}">${row.mapped?'MAPPED':'MISSING'}</span></td><td><strong>${esc(row.classCode)}</strong><br><small>${esc(row.term)}</small></td><td>${esc(row.name)}</td><td>${esc(row.instructor||'-')}</td><td class="source">${esc(row.source||'-')}</td></tr>`).join('');}
async function refresh(download=false){log('info',download?'공식 데이터를 준비하고 mapping 판독을 시작합니다.':'mapping 상태를 다시 읽습니다.');const college=$('college').value;const data=download?await api('/api/load',{method:'POST',body:JSON.stringify({college})}):await api(`/api/status?college=${encodeURIComponent(college)}`);renderStatus(data);}
$('refresh').onclick=()=>refresh(false);$('loadData').onclick=()=>refresh(true);$('college').onchange=()=>refresh(false);$('classSearch').oninput=renderClasses;$('statusFilter').onchange=renderClasses;
$('copyNextBatch').onclick=async()=>{if(!state.status?.ok)return;const n=Math.max(1,Math.min(200,Number($('batchSize').value)||50));const rows=state.status.classes.filter(row=>!row.mapped).slice(0,n);const text=rows.map(row=>`${row.classCode}\t${row.name}\t${row.instructor||''}`).join('\n');if(!text){log('warn','복사할 미매핑 Class가 없습니다.');return}await navigator.clipboard.writeText(text);log('ok',`다음 미매핑 ${rows.length}개 Class를 클립보드에 복사했습니다.`);};
$('validate').onclick=async()=>{log('info','붙여넣은 링크 검증을 시작합니다.');const data=await api('/api/validate',{method:'POST',body:JSON.stringify({college:$('college').value,text:$('input').value})});events(data.events);if(!data.ok){log('error',data.error||'검증 실패');return}state.accepted=data.accepted||{};$('jsonOutput').textContent=data.json||'{}';$('copyJson').disabled=Object.keys(state.accepted).length===0;$('saveBatch').disabled=Object.keys(state.accepted).length===0;log(Object.keys(state.accepted).length?'ok':'warn',`검증 완료: 새 링크 ${Object.keys(state.accepted).length}, rejected ${(data.rejected||[]).length}, duplicate ${(data.duplicates||[]).length}`);};
$('copyJson').onclick=async()=>{await navigator.clipboard.writeText($('jsonOutput').textContent);log('ok','검증된 JSON을 클립보드에 복사했습니다.');};
$('saveBatch').onclick=async()=>{const data=await api('/api/save-batch',{method:'POST',body:JSON.stringify({college:$('college').value,batchName:$('batchName').value,entries:state.accepted})});events(data.events);if(!data.ok){log('error',data.error||'저장 실패');return}log('ok',`${data.path} 저장 완료`);state.accepted={};$('copyJson').disabled=true;$('saveBatch').disabled=true;renderStatus(data.status);};
$('clearLog').onclick=()=>$('log').innerHTML='';$('copyLog').onclick=async()=>{const text=[...$('log').querySelectorAll('.log-line')].map(x=>x.textContent).join('\n');await navigator.clipboard.writeText(text);log('ok','Output Log를 클립보드에 복사했습니다.');};
refresh(false);
